const ACCESS_TOKEN_DURATION = "30m";
const REFRESH_TOKEN_DURATION = "30d";
const ONE_DAY_IN_MILLISECONDS = 24 * 60 * 60 * 1000;

const USER_IMAGE_DESTINATION = "images/users/";

const ECG_IMAGE_DESTINATION = "images/ecgs/";
const ECG_REPORT_DESTINATION = "images/bad_digitization/";

const SCAN_DESTINATION = (id) => `images/temp_${id}/`;
const SCAN_REPORT_DESITNATION = "images/bad_scans/";

const CONCURRENT_SCANS_LIMIT = 20
const CONCURRENT_DIGITIZING_LIMIT = 5

module.exports = {
  ACCESS_TOKEN_DURATION,
  REFRESH_TOKEN_DURATION,
  ONE_DAY_IN_MILLISECONDS,
  USER_IMAGE_DESTINATION,
  ECG_IMAGE_DESTINATION,
  ECG_REPORT_DESTINATION,
  SCAN_DESTINATION,
  SCAN_REPORT_DESITNATION,
  CONCURRENT_SCANS_LIMIT,
  CONCURRENT_DIGITIZING_LIMIT
};
