const ACCESS_TOKEN_DURATION = "30m";
const REFRESH_TOKEN_DURATION = "30d";
const ONE_DAY_IN_MILLISECONDS = 24 * 60 * 60 * 1000;

module.exports = {
  ACCESS_TOKEN_DURATION,
  REFRESH_TOKEN_DURATION,
  ONE_DAY_IN_MILLISECONDS,
};
