const ACCESS_TOKEN_DURATION = "30m";
const REFRESH_TOKEN_DURATION = "30d";
const ONE_DAY_IN_MILLISECONDS = 24 * 60 * 60 * 1000;

const USER_IMAGE_DESTINATION = "images/users/";
const ECG_IMAGE_DESTINATION = "images/ecgs/";

module.exports = {
  ACCESS_TOKEN_DURATION,
  REFRESH_TOKEN_DURATION,
  ONE_DAY_IN_MILLISECONDS,
  USER_IMAGE_DESTINATION,
  ECG_IMAGE_DESTINATION,
};
